server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      config: |
        ui = true
        
        storage "raft" {
          path = "/vault/data"
        }
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = "true"
        }
        api_addr = "http://${POD_NAME}.vault-internal:8200"
        cluster_addr = "https://_POD_IP_:8201"
  dev:
    enabled: false
